### ISSUE TITLE
Is there a way to bind proxy into account?

### ISSUE THREAD

**Issue by stoneycreeky** [MsLolita/backpack-volume-auto#1]
As key:secret:proxy
thanks

**Comment by MsLolita** [comment]
Check last line in README.md file, where is writing how to bind proxy. 1-st line in accounts.txt take 1-st line in proxies.txt and so on

**Comment by stoneycreeky** [comment]
I see, thanks for clarification!  Brilliant!  

Also is there any plan to enhance the client (like grid ) to reduce the transaction fee?
