### ISSUE TITLE
In what format should the proxy be entered?

### ISSUE THREAD

**Issue by Zalupin777** [MsLolita/backpack-volume-auto#6]
ip:port:user:pass   does not work

**Comment by 0xMeXoo** [comment]
user:pass@ip:port

**Comment by Zalupin777** [comment]
I enter proxies in different formats, the software gives an error, everything works without a proxy, a proxy also works separately, what could be the problem?

**Comment by MsLolita** [comment]
> I enter proxies in different formats, the software gives an error, everything works without a proxy, a proxy also works separately, what could be the problem?

proxies doesn't fits for backpack api, [nice proxies](https://teletype.in/@web3enjoyer/4a2G9NuHssy) wil fits.
