### ISSUE TITLE
Запрос на улучшения

### ISSUE THREAD

**Issue by defigeneration** [MsLolita/backpack-volume-auto#8]
Не мог бы ты сделать пожалуйста автоматический клейм THE DROP после прокрута объема
и добавить новые пары? TNSR/USDC, PRCL/USDC?

**Comment by MsLolita** [comment]
ку, добавить пары не проблема (их просто закинул в конфиг и бот будет юзать, мне необязательно в коде ничего менять и так будет воркать), а вот клейм дропа не сделаю, потому что из-за их апи это невозможно, надо писать другой софт, который будет логиниться по емейлу и паролю, получать куки и так уже клеймить дроп, поэтому пока никак.
